Fix report info_text for functions w/ multiple non-string args
Passing a function with multiple arguments to `energyusage.evaluate()` causes an error if any args are not strings:
```
numpy.core._exceptions.UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
```

Fixed report generation by casting each `arg` to string, as well as improving formatting for `np.ndarray` arg types 💪